import React from 'react'
import { useTranslation } from 'i18n'

const Privacy = () => {
    const { t } = useTranslation()
    return (
        <div className="wrapper-privacyPolicy">
            <h2 className="uzdPrivacy">{t('privacy_policy_for_uzd')}</h2>
            <h1>{t('privacy_policy')}</h1>
            <p>{t('last_updated')}</p>
            <p>{t('privacy_first_text')}</p>
            <p>
                {t('privacy_second_text')}{' '}
                <a
                    href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/"
                    target="_blank"
                    rel="noreferrer"
                >
                    {t('free_privacy_generator')}
                </a>
                .
            </p>
            <h1>{t('interprettions_definitions')}</h1>
            <h2>{t('interpretation')}</h2>
            <p>{t('privacy_third_text')}</p>
            <h2>{t('definitions')}</h2>
            <p>{t('purpose_for_privacy')}</p>
            <ul>
                <li>
                    <p>
                        <strong>{t('account')}</strong>
                        {t('li_text_first')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('company')}</strong>
                        {t('li_text_second')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('cookies')}</strong>
                        {t('li_text_third')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('country')}</strong>
                        {t('refers_to_uzbekistan')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('device')}</strong>
                        {t('li_text_fourth')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('personal_data')}</strong>
                        {t('li_text_fifth')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('service')}</strong>
                        {t('refers_to_website')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('service_provider')}</strong>
                        {t('li_text_sixth')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('usage_data')}</strong>
                        {t('li_text_seventh')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('website')}</strong>
                        {t('li_text_eighth')}{' '}
                        <a
                            href="uzd.udevs.io"
                            rel="external nofollow noopener"
                            target="_blank"
                        >
                            uzd.udevs.io
                        </a>
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('you')}</strong>
                        {t('li_text_nineth')}
                    </p>
                </li>
            </ul>
            <h1>{t('collecting_personal_data')}</h1>
            <h2>{t('types_data_collected')}</h2>
            <h3>{t('personal_data')}</h3>
            <p>{t('privacy_fourth_text')}</p>
            <ul>
                <li>
                    <p>{t('email_address')}</p>
                </li>
                <li>
                    <p>{t('fisrtName_lastName')}</p>
                </li>
                <li>
                    <p>{t('tell_number')}</p>
                </li>
                <li>
                    <p>{t('usage_data')}</p>
                </li>
            </ul>
            <h3>{t('usage_data')}</h3>
            <p>{t('automatically_collected_data')}</p>
            <p>{t('privacy_fifth_text')}</p>
            <p>{t('privacy_sixth_text')}</p>
            <p>{t('privacy_seventh_text')}</p>
            <h3>{t('technologies_cookies')}</h3>
            <p>{t('privacy_eighth_text')}</p>
            <ul>
                <li>
                    <strong>{t('cookiesOr_browserCookies')}</strong>{' '}
                    {t('privacy_nineth_text')}
                </li>
                <li>
                    <strong>{t('flash_cookies')}</strong>{' '}
                    {t('privacy_tenth_text')}{' '}
                    <a
                        href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"
                        rel="external nofollow noopener noreferrer"
                        target="_blank"
                    >
                        https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_
                    </a>
                </li>
                <li>
                    <strong>{t('web_beacons')}</strong>
                    {t('privacy_eleventh_text')}
                </li>
            </ul>
            <p>
                {t('privacy_twelveth_text')}{' '}
                <a
                    href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking"
                    target="_blank"
                    rel="noreferrer"
                >
                    {t('free_privacy_website')}
                </a>{' '}
                {t('article')}
            </p>
            <p>{t('privacy_theertenth_text')}</p>
            <ul>
                <li>
                    <p>
                        <strong>{t('nessessary_essential')}</strong>
                    </p>
                    <p>{t('type_cookies')}</p>
                    <p>{t('administered_by')}</p>
                    <p>{t('privacy_fourtenth_text')}</p>
                </li>
                <li>
                    <p>
                        <strong>{t('cookies_policy')}</strong>
                    </p>
                    <p>{t('persistent_cookies')}</p>
                    <p>{t('administered_by')}</p>
                    <p>{t('privacy_fifthtenth_text')}</p>
                </li>
                <li>
                    <p>
                        <strong>{t('functionality_cookies')}</strong>
                    </p>
                    <p>{t('persistent_cookies')}</p>
                    <p>{t('administered_by')}</p>
                    <p>{t('privacy_sixtenth_text')}</p>
                </li>
            </ul>
            <p>{t('privacy_sevententh_text')}</p>
            <h2>{t('use_your_data')}</h2>
            <p>{t('privacy_eighttenth_text')}</p>
            <ul>
                <li>
                    <p>
                        <strong>{t('provide_maintain')}</strong>
                        {t('privacy_nenitenth_text')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('manage_accout')}</strong>
                        {t('privacy_twentyth_text')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('performance_contact')}</strong>
                        {t('privacy_twentyoneth_text')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('contact_you')}</strong>{' '}
                        {t('privacy_twentytwoth_text')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('provide_you')}</strong>{' '}
                        {t('privacy_twentythreeth_text')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('manage_request')}</strong>
                        {t('attend_manage')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('business_transfers')}</strong>
                        {t('privacy_twentyfourth_text')}
                    </p>
                </li>
                <li>
                    <p>
                        <strong>{t('other_purpose')}</strong>
                        {t('privacy_twentyfifth_text')}
                    </p>
                </li>
            </ul>
            <p>{t('privacy_twentysixth_text')}</p>
            <ul>
                <li>
                    <strong>{t('service_providers')}</strong>
                    {t('privacy_twentyseventh_text')}
                </li>
                <li>
                    <strong>{t('business_transfers')}</strong>
                    {t('privacy_twentyeighth_text')}
                </li>
                <li>
                    <strong>{t('with_affiliates')}</strong>
                    {t('privacy_twentynineth_text')}
                </li>
                <li>
                    <strong>{t('with_partners')}</strong>
                    {t('privacy_thirty_text')}
                </li>
                <li>
                    <strong>{t('other_users')}</strong>
                    {t('privacy_thirtyone_text')}
                </li>
                <li>
                    <strong>{t('consent')}</strong>
                    {t('privacy_thirtytwo_text')}
                </li>
            </ul>
            <h2>{t('retention_data')}</h2>
            <p>{t('privacy_thirtythree_text')}</p>
            <p>{t('privacy_thirtyfour_text')}</p>
            <h2>{t('transfer_data')}</h2>
            <p>{t('privacy_thirtyfive_text')}</p>
            <p>{t('privacy_thirtysix_text')}</p>
            <p>{t('privacy_thirtyseven_text')}</p>
            <h2>{t('disclosure_data')}</h2>
            <h3>{t('business_transaction')}</h3>
            <p>{t('privacy_thirtyeight_text')}</p>
            <h3>{t('law_enforcement')}</h3>
            <p>{t('privacy_thirtynine_text')}</p>
            <h3>{t('legal_requirements')}</h3>
            <p>{t('privacy_fourty_text')}</p>
            <ul>
                <li>{t('privacy_fourtyone_text')}</li>
                <li>{t('protect_defend')}</li>
                <li>{t('prevent_investigate')}</li>
                <li>{t('personal_safety')}</li>
                <li>{t('legal_liability')}</li>
            </ul>
            <h2>{t('security_data')}</h2>
            <p>{t('privacy_fourtytwo_text')}</p>
            <h1>{t('childrens_privacy')}</h1>
            <p>{t('privacy_fourtythree_text')}</p>
            <p>{t('privacy_fourtyfour_text')}</p>
            <h1>{t('link_other_websites')}</h1>
            <p>{t('privacy_fourtyfive_text')}</p>
            <p>{t('privacy_fourtysix_text')}</p>
            <h1>{t('change_policy')}</h1>
            <p>{t('privacy_fourtyseven_text')}</p>
            <p>{t('privacy_fourtyeight_text')}</p>
            <p>{t('privacy_fourtynine_text')}</p>
            <h1>{t('contact_us')}</h1>
            <p>{t('privacy_fifty_text')}</p>
            <ul>
                <li>{t('by_email')} bobur.abomuslimov123@gmail.com</li>
            </ul>
        </div>
    )
}

export default Privacy
